/* Recipe tree notation: a number is an ingredient row (index into ing); an array is [step, ...inputs].
   Each step sits one column right of its deepest input and spans the rows of everything it combines. */
const RECIPES = [
  { id:"salsa", name:"Salsa Chicken Burrito Filling", app:"crockpot", serves:8, kcal:293, p:43, c:17, f:5, bg:"#d9482b", food:["#f2c14e","#2b1d14","#fff3dc"],
    src:{ site:"Food.com", title:"Salsa Chicken in the Crock Pot", url:"https://www.food.com/recipe/salsa-chicken-in-the-crock-pot-185854", stars:null, n:7 },
    ing:[[[[3, "lb", 1361]], "boneless skinless chicken breasts"], [[[2, "jar (14 oz)", 794]], "salsa"], [[[1, "can (15 oz)", 425]], "black beans, drained"], [[[1, "can (15 oz)", 425]], "corn, drained"]],
    tree:["warm through 15–20 min",["shred with 2 forks",["cook on HIGH 4½–5 h",0,1]],2,3],
    post:["Serve in tortillas, over rice or on salad"] },
  { id:"chili", name:"Turkey Chili", app:"crockpot", serves:10, kcal:272, p:31, c:31, f:4, bg:"#8f2d1c", food:["#b5482a","#6b3a26","#fff8ea"],
    src:{ site:"Two Peas & Their Pod", title:"Slow Cooker Turkey Chili", url:"https://www.twopeasandtheirpod.com/slow-cooker-turkey-chili/", stars:4.68, n:148 },
    change:"We doubled the turkey to 2 lb for more protein per bowl.",
    ing:[[[[1, "tbsp", 13.5]], "olive oil"], [[[2, "lb", 907]], "99% lean ground turkey"], [[[1, "medium", 150]], "onion, diced"], [[[1, "", 150]], "red bell pepper, chopped"], [[[1, "", 150]], "yellow bell pepper, chopped"], [[[30, "oz", 850]], "tomato sauce"], [[[30, "oz", 850]], "petite diced tomatoes"], [[[30, "oz", 850]], "black beans, rinsed and drained"], [[[30, "oz", 850]], "red kidney beans, rinsed and drained"], [[[1, "jar (16 oz)", 454]], "tamed jalapeño slices, drained"], [[[1, "cup", 140]], "frozen corn"], [[[2, "tbsp", 16]], "chili powder"], [[[1, "tbsp", 6]], "ground cumin"], [[["to taste", "", null]], "salt and black pepper"]],
    tree:["cook on HIGH 4 h or LOW 6 h",["stir together",["brown in skillet",0,1],2,3,4,5,6,7,8,9,10,11,12,13]],
    post:["Top with Greek yogurt, green onion or cheese"] },
  { id:"barbacoa", name:"Beef Barbacoa", app:"crockpot", serves:8, kcal:210, p:30, c:3, f:9, bg:"#6b3a26", food:["#8a4a2c","#4f7a2e","#f4ead7"],
    src:{ site:"The Real Food Dietitians", title:"Slow Cooker Beef Barbacoa", url:"https://therealfooddietitians.com/slow-cooker-beef-barbacoa/", stars:5, n:8 },
    ing:[[[[2.5, "lb", 1134]], "beef chuck roast, fat trimmed, cut in 2-inch cubes"], [[[0.5, "cup", 120.0]], "water"], [[[0.5, "medium", 75.0]], "yellow onion, quartered"], [[[6, "", 24]], "garlic cloves"], [[[3, "tbsp", 48]], "tomato paste"], [[[2.5, "tbsp", 37.5]], "lime juice"], [[[1, "tbsp", 6]], "ground cumin"], [[[1, "tbsp", 3]], "dried oregano"], [[[0.75, "tsp", 4.5], [0.25, "tsp", 0.6]], "salt and black pepper"], [[["pinch each", "", null]], "ground cloves and chipotle powder"], [[[3, "", null]], "bay leaves"]],
    tree:["shred, stir into juices",["cook on LOW 7 h or HIGH 3½ h",0,["blend smooth",1,2,3,4,5,6,7,8,9],10]],
    post:["Use for tacos, burrito bowls or salads"] },
  { id:"tikka", name:"Chicken Tikka Masala", app:"crockpot", serves:6, kcal:346, p:44, c:18, f:12, bg:"#e07a1f", food:["#e8a03a","#fff8ea","#4f7a2e"],
    src:{ site:"The Recipe Critic", title:"Slow Cooker Chicken Tikka Masala", url:"https://therecipecritic.com/slow-cooker-chicken-tikka-masala/", stars:4.29, n:14 },
    change:"We swapped 1 cup heavy cream for ½ cup half-and-half and used nonfat Greek yogurt.",
    ing:[[[[1, "small", 110]], "onion, chopped"], [[[3, "", 12]], "garlic cloves, minced"], [[[2, "tbsp", 12]], "fresh ginger, grated"], [[[1, "can (29 oz)", 822]], "tomato purée"], [[[1.5, "cup", 367.5]], "plain nonfat Greek yogurt"], [[[2, "tbsp", 27.0]], "olive oil"], [[[2, "tbsp", 12]], "garam masala"], [[[1, "tbsp", 6]], "ground cumin"], [[[0.5, "tbsp", 3.5], [0.75, "tsp", 2.0], [1, "tsp", 1.8]], "paprika, cinnamon, cayenne"], [[[2, "tsp", 12], [0.75, "tsp", 1.7]], "salt and black pepper"], [[[2, "lb", 907]], "chicken breasts, 1-inch pieces"], [[[2, "", null]], "bay leaves"], [[[0.5, "cup", 121.0]], "half-and-half"], [[[0.5, "tbsp", 4.0]], "cornstarch"]],
    tree:["cook 20 min more",["cook on LOW 6 h or HIGH 4 h",["toss to coat",["stir together",0,1,2,3,4,5,6,7,8,9],10],11],["whisk",12,13]],
    post:["Serve over basmati rice with cilantro"] },
  { id:"whitechili", name:"White Chicken Chili", app:"crockpot", serves:6, kcal:393, p:46, c:33, f:8, bg:"#c9a24a", food:["#f4ead7","#e8c77a","#4f7a2e"], isNew:true,
    src:{ site:"Food.com", title:"Crock Pot White Chicken Chili", url:"https://www.food.com/recipe/crock-pot-white-chicken-chili-114789", stars:5, n:167 },
    change:"We raised the chicken from 1¼ to 2 lb and swapped sour cream for Greek yogurt.",
    ing:[[[[2, "lb", 907]], "boneless skinless chicken breasts"], [[[2, "can (15 oz)", 850]], "great northern beans, drained"], [[[1, "can (15 oz)", 425]], "white hominy or white corn, drained"], [[[1, "packet (1¼ oz)", 35]], "taco seasoning"], [[[1, "can (4½ oz)", 128]], "chopped green chiles"], [[[1, "can (10¾ oz)", 305]], "condensed cream of chicken soup"], [[[1, "can (14 oz)", 397]], "chicken broth"], [[[0.5, "cup", 122.5]], "plain Greek yogurt"]],
    tree:["stir in",["break up chicken",["cook on LOW 8–10 h",["layer in pot",0,1,2],["mix, pour over",3,4,5,6]]],7],
    post:["Top with green onion and Monterey Jack"] },
  { id:"honeygarlic", name:"Honey Garlic Chicken", app:"crockpot", serves:6, kcal:280, p:37, c:24, f:4, bg:"#b5651d", food:["#d98e3a","#fff3dc","#4f7a2e"], isNew:true,
    src:{ site:"Le Crème de la Crumb", title:"Slow Cooker Honey Garlic Chicken", url:"https://www.lecremedelacrumb.com/slow-cooker-honey-garlic-chicken/", stars:4.91, n:20 },
    ing:[[[[2, "lb", 907]], "boneless skinless chicken breasts"], [[[0.5, "cup", 127.5]], "low-sodium soy sauce"], [[[0.5, "cup", 120.0]], "ketchup"], [[[0.3333333333333333, "cup", 113.3]], "honey"], [[[2, "tsp", 10]], "hot sauce"], [[[1, "tbsp", 15]], "minced garlic"], [[[1, "tsp", 1]], "Italian seasoning"]],
    tree:["cook on LOW 6 h",0,["whisk, pour over",1,2,3,4,5,6]],
    post:["Serve over rice with steamed broccoli"] },

  { id:"salmon", name:"Honey-Soy Salmon Bites", app:"airfryer", serves:3, kcal:390, p:32, c:8, f:25, bg:"#f08a6c", food:["#f4a582","#3d2a1e","#4f7a2e"],
    src:{ site:"Chef Savvy", title:"Air Fryer Salmon Bites", url:"https://chefsavvy.com/air-fryer-salmon-bites/", stars:5, n:1 },
    pre:["Preheat air fryer to 400°F; spray basket"],
    ing:[[[[1, "lb", 454]], "salmon, cut in 1-inch cubes"], [[[3, "tbsp", 48]], "low-sodium soy sauce"], [[[1, "tbsp", 13.5]], "sesame oil"], [[[1, "tbsp", 21]], "honey"], [[[4, "", 16]], "garlic cloves, minced"], [[[1, "tsp", 6]], "sriracha"], [[["sprinkle", "", null]], "sesame seeds, to garnish"]],
    tree:["spoon on saved sauce, top",["air fry 8 min",["toss",0,["whisk; save 2 tbsp",1,2,3,4,5]]],6],
    post:["Serve with rice and vegetables"] },
  { id:"parm", name:"Parmesan-Crusted Chicken", app:"airfryer", serves:4, kcal:405, p:51, c:7, f:18, bg:"#d9a03a", food:["#e3b25a","#c98f0a","#4f7a2e"],
    src:{ site:"Air Frying Foodie", title:"Air Fryer Parmesan Crusted Chicken", url:"https://airfryingfoodie.com/air-fryer-parmesan-crusted-chicken/", stars:4.72, n:38 },
    change:"Doubled from 2 to 4 servings.",
    pre:["Preheat air fryer to 380°F"],
    ing:[[[[4, "", 800]], "boneless skinless chicken breasts (6–8 oz each)"], [[[0.25, "cup", 57.5]], "sour cream or Greek yogurt"], [[[0.5, "cup", 30.0]], "Italian-style panko"], [[[0.5, "cup", 50.0]], "grated Parmesan"], [[[1, "tsp", 2.3]], "paprika"], [[[0.5, "tsp", 1.5], [0.5, "tsp", 1.1]], "kosher salt and black pepper"], [[[2, "tsp", 9.0]], "olive oil, for the basket"]],
    tree:["air fry 12 min, flip, 4–6 min to 165°F",["press onto tops",["spread on tops",0,1],["mix",2,3,4,5]],6],
    post:["Serve with a big salad or roasted vegetables"] },
  { id:"meatballs", name:"Turkey Meatballs", app:"airfryer", serves:6, kcal:291, p:32, c:8, f:14, bg:"#b8452c", food:["#9c5a3a","#d9482b","#4f7a2e"],
    src:{ site:"Food Lovin Family", title:"Air Fryer Turkey Meatballs", url:"https://www.foodlovinfamily.com/air-fryer-turkey-meatballs/", stars:4.89, n:36 },
    change:"Doubled to 2 lb so it makes 6 hearty servings.",
    pre:["Preheat air fryer to 400°F; spray basket"],
    ing:[[[[2, "lb", 907]], "ground turkey (93% lean)"], [[[1, "cup", 60]], "panko breadcrumbs"], [[[2, "", 100]], "eggs"], [[[0.5, "cup", 15.0]], "fresh parsley, chopped"], [[[2, "tbsp", 32]], "low-sodium soy sauce"], [[["to taste", "", null]], "black pepper"]],
    tree:["air fry in batches: 5 min, flip, 5 min",["roll into 1½-inch balls",["mix gently",0,1,2,3,4,5]]],
    post:["Serve with marinara and zucchini noodles"] },
  { id:"shrimp", name:"Cajun Shrimp & Sausage", app:"airfryer", serves:4, kcal:262, p:32, c:7, f:12, bg:"#e2643a", food:["#f39a6b","#fff3dc","#4f7a2e"],
    src:{ site:"Skinnytaste", title:"Air Fryer Cajun Shrimp Dinner", url:"https://www.skinnytaste.com/air-fryer-cajun-shrimp-dinner/", stars:4.93, n:157 },
    pre:["Preheat air fryer to 400°F"],
    ing:[[[[1, "lb", 454]], "extra-jumbo shrimp, peeled"], [[[1, "tbsp", 7]], "Cajun or Creole seasoning"], [[[6, "oz", 170]], "cooked chicken or turkey andouille, sliced"], [[[1, "", 227]], "zucchini, ¼-inch half moons"], [[[1, "", 227]], "yellow squash, ¼-inch half moons"], [[[1, "large", 180]], "red bell pepper, 1-inch pieces"], [[[0.25, "tsp", 0.8]], "kosher salt"], [[[2, "tbsp", 27.0]], "olive oil"]],
    tree:["air fry 2 batches × 8 min, shaking; combine, 1 min",["toss",["toss to coat",0,1],2,3,4,5,6,7]],
    post:["Serve as is or over rice"] },
  { id:"tofu", name:"Crispy Tofu & Edamame", app:"airfryer", serves:4, kcal:400, p:38, c:24, f:18, veg:true, bg:"#6f8f3a", food:["#e8c77a","#7fae4a","#2b1d14"],
    src:{ site:"Nora Cooks", title:"Air Fryer Tofu", url:"https://www.noracooks.com/air-fryer-tofu/", stars:4.98, n:36 },
    change:"Doubled the tofu and added 1 cup edamame per serving for a full meal.",
    ing:[[[[2, "block (14 oz)", 794]], "extra-firm tofu"], [[[0.25, "cup", 63.8]], "low-sodium soy sauce or tamari"], [[[2, "tbsp", 30]], "seasoned rice vinegar"], [[[2, "tsp", 9.0]], "sesame oil"], [[[2, "tbsp", 16]], "cornstarch"], [[[4, "cup", 620]], "shelled edamame"]],
    tree:["serve together",["air fry 400°F 10–15 min, shake at 10",["coat; rest 15 min",["drizzle, toss gently",["press 15 min, cube",0],1,2,3],4]],["steam or microwave",5]],
    post:["Add rice and a drizzle of sriracha"] },
  { id:"fajitas", name:"Chicken Fajitas", app:"airfryer", serves:4, kcal:337, p:40, c:9, f:15, bg:"#c0392b", food:["#e8b04a","#3f7a2e","#f4ead7"], isNew:true,
    src:{ site:"The Big Man's World", title:"Air Fryer Chicken Fajitas", url:"https://thebigmansworld.com/air-fryer-chicken-fajitas/", stars:5, n:1 },
    pre:["Preheat air fryer to 400°F"],
    ing:[[[[3, "tbsp", 40.5]], "olive oil"], [[[3, "", 12]], "garlic cloves, minced"], [[[1, "tsp", 2]], "ground cumin"], [[[1, "tsp", 2.3]], "smoked paprika"], [[[1, "tsp", 2.7]], "chili powder"], [[[0.5, "tsp", 1.2], [0.5, "tsp", 0.5]], "onion powder and dried oregano"], [[[1, "tsp", 6], [0.5, "tsp", 1.1]], "salt and black pepper"], [[[1.5, "lb", 680]], "chicken breasts, ½-inch strips"], [[[3, "", 450]], "bell peppers, ½-inch strips"], [[[1, "large", 225]], "white onion, ½-inch strips"]],
    tree:["air fry 8 min, shake, 4 min to 165°F",["toss by hand",["mix",0,1,2,3,4,5,6],7,8,9]],
    post:["Serve in warm tortillas or over rice"] },

  { id:"flank", name:"Chimichurri Flank Steak", app:"grill", serves:4, kcal:333, p:36, c:2, f:20, bg:"#3b2a20", food:["#8a3b2a","#4f7a2e","#f4ead7"],
    change:"The source splits this into 6 small servings (24 g protein each). We count it as 4 so a serving reaches about 36 g.",
    src:{ site:"Skinnytaste", title:"Grilled Chimichurri Steak", url:"https://www.skinnytaste.com/grilled-flank-steak-with-chimichurri/", stars:4.95, n:36 },
    pre:["Heat grill to high"],
    ing:[[[[1.5, "lb", 680]], "flank steak"], [[[1, "tsp", 3]], "garlic powder"], [[[0.75, "tsp", 1.5]], "ground cumin"], [[[0.5, "tsp", 0.5]], "dried oregano"], [[[1.25, "tsp", 3.8]], "kosher salt, plus black pepper"], [[[0.3333333333333333, "cup", 20.0]], "fresh parsley, packed, minced"], [[[2, "tbsp", 20]], "red onion, finely chopped"], [[[4, "", 16]], "garlic cloves, minced"], [[[2, "tbsp", 27.0]], "extra-virgin olive oil"], [[[3, "tbsp", 45]], "red wine vinegar"], [[[1, "tbsp", 15]], "water"], [[[0.25, "tsp", 1.5], [0.125, "tsp", 0.3], [0.125, "tsp", 0.2]], "salt, pepper, red pepper flakes"]],
    tree:["spoon sauce over",["slice across grain",["grill 3–4 min/side; rest 5 min",["season both sides",["score ⅛ inch deep",0],["mix",1,2,3,4]]]],["mix",5,6,7,8,9,10,11]],
    post:["Serve with potatoes or over greens"] },
  { id:"souvlaki", name:"Chicken Souvlaki & Tzatziki", app:"grill", serves:4, kcal:381, p:42, c:5, f:21, bg:"#2f6f8f", food:["#d9a066","#fff8ea","#4f7a2e"],
    src:{ site:"RecipeTin Eats", title:"Chicken Souvlaki", url:"https://www.recipetineats.com/chicken-souvlaki/", stars:4.94, n:47 },
    pre:["Heat grill or skillet to high"],
    ing:[[[[1.5, "lb", 680]], "chicken thighs, 1-inch pieces"], [[[2, "tbsp", 27.0]], "olive oil"], [[[0.25, "cup", 60.0]], "lemon juice"], [[[3, "", 12]], "garlic cloves, minced"], [[[2, "tbsp", 6]], "dried oregano"], [[[0.625, "tsp", 3.8]], "salt, plus black pepper"], [[[1, "tbsp", 13.5]], "olive oil, for cooking"], [[[2, "small", 240]], "cucumbers"], [[[1.25, "cup", 300.0]], "plain Greek yogurt"], [[[2, "tsp", 10]], "white wine vinegar"], [[[1, "tbsp", 15]], "lemon juice"], [[[0.5, "", 2.0]], "garlic clove, minced"], [[[1, "tbsp", 13.5]], "extra-virgin olive oil"], [[[0.5, "tsp", 3.0]], "salt, plus black pepper"]],
    tree:["serve together",["grill 3 min/side",["thread on 8 skewers",["marinate 3 h to overnight",0,1,2,3,4,5]],6],["mix; rest 20 min",["seed, grate, squeeze dry",7],8,9,10,11,12,13]],
    post:["Serve with pita, lettuce and tomato"] },
  { id:"pork", name:"Spice-Rubbed Pork Tenderloin", app:"grill", serves:6, kcal:232, p:33, c:7, f:8, bg:"#a34a2a", food:["#c77b52","#f4ead7","#4f7a2e"],
    src:{ site:"Fed & Fit", title:"Best Pork Tenderloin Rub", url:"https://fedandfit.com/best-pork-tenderloin-rub/", stars:4.45, n:56 },
    change:"Rub doubled for two tenderloins. Grill method follows The Wooden Skillet's grilled pork tenderloin.",
    pre:["Heat grill to medium-high (350–450°F)"],
    ing:[[[[2, "", 908]], "pork tenderloins (about 1 lb each)"], [[[1, "tbsp", 13.5]], "olive oil"], [[[2, "tbsp", 16]], "chili powder"], [[[2, "tbsp", 26]], "brown or coconut sugar"], [[[1, "tbsp", 3]], "dried oregano"], [[[1, "tbsp", 7]], "paprika"], [[[1, "tsp", 2.6]], "ground cinnamon"], [[[1, "tsp", 3]], "garlic powder"], [[[1, "tsp", 6]], "sea salt"]],
    tree:["rest 5 min; slice",["grill, turning every 3–4 min, to 145°F (about 25 min)",["rub all over",["pat dry, brush",0,1],["mix",2,3,4,5,6,7,8]]]],
    post:["Serve with grilled vegetables or sweet potato"] },
  { id:"teriyaki", name:"Grilled Teriyaki Chicken", app:"grill", serves:4, kcal:226, p:29, c:5, f:9, bg:"#5a2e1a", food:["#8a4a2c","#f4ead7","#4f7a2e"], isNew:true,
    src:{ site:"The Big Man's World", title:"Grilled Teriyaki Chicken", url:"https://thebigmansworld.com/grilled-teriyaki-chicken/", stars:5, n:3 },
    pre:["Heat grill to medium; oil the grates"],
    ing:[[[[3, "tbsp", 48]], "soy sauce"], [[[1, "tbsp", 13]], "brown sugar or honey"], [[[1, "tbsp", 15]], "rice wine vinegar"], [[[1, "tbsp", 13.5]], "sesame oil"], [[[2, "", 8]], "garlic cloves, minced"], [[[1, "tsp", 2]], "fresh ginger, minced"], [[[4, "", 568]], "boneless chicken thighs (about 5 oz each)"], [[[1, "tsp", 2.7]], "cornstarch"]],
    tree:["brush on, serve",["grill 5 min/side to 165°F",["marinate 10 min to 24 h",["whisk",0,1,2,3,4,5],6]],["simmer with leftover marinade 2–3 min",7]],
    post:["Serve with rice and grilled pineapple"] },
  { id:"burger", name:"Juicy Lean Burgers", app:"grill", serves:6, kcal:246, p:33, c:4, f:10, bg:"#c98f0a", food:["#6b3a26","#e8b04a","#4f7a2e"],
    src:{ site:"Teaspoon of Spice", title:"The Juiciest Lean Beef Burgers", url:"https://teaspoonofspice.com/juiciest-lean-beef-burgers/", stars:null, n:null },
    change:"Formed into 6 patties instead of 8 for about 33 g protein each.",
    pre:["Heat grill to medium"],
    ing:[[[[1, "tbsp", 13.5]], "canola oil"], [[[2, "large", 450]], "onions, chopped"], [[[2, "lb", 907]], "95% lean ground beef"], [[[1.5, "tbsp", 25.5]], "Worcestershire sauce"], [[["to taste", "", null]], "black pepper"]],
    tree:["grill covered 11–15 min to 160°F",["form 6 patties, press firmly",["mix by hand",["cook 5 min; cover, low, 15 min; cool",0,1],2,3,4]]],
    post:["Bun adds about 130 kcal and 6 g protein"] },

  { id:"pancakes", name:"Cottage Cheese Pancakes", app:"griddle", cat:"sweet", serves:4, kcal:363, p:22, c:39, f:13, bg:"#d9a560", food:["#e8b878","#a16207","#c0392b"], isNew:true,
    src:{ site:"Feel Good Foodie", title:"Fluffy Cottage Cheese Pancakes", url:"https://www.feelgoodfoodie.net/recipe/cottage-cheese-pancakes/", stars:4.99, n:101 },
    change:"We swapped ¼ cup of the flour for a scoop of vanilla whey (+6 g protein per serving).",
    pre:["Heat a buttered skillet or griddle over medium"],
    ing:[[[[4, "large", 200]], "eggs"], [[[1, "cup", 225]], "cottage cheese"], [[[0.25, "cup", 61.0]], "milk"], [[[3, "tbsp", 60]], "maple syrup"], [[[1, "tsp", 4]], "vanilla extract"], [[[1, "cup", 125]], "all-purpose flour"], [[[1, "scoop", 30]], "vanilla whey protein"], [[[1, "tsp", 4]], "baking powder"], [[[0.5, "tsp", 1.3]], "cinnamon"], [[[2, "tbsp", 28.4]], "butter, melted"]],
    tree:["cook ¼-cup mounds 2–3 min/side",["stir in; rest 10 min",["whisk together",["whisk",0,1,2,3,4],["sift in",5,6,7,8]],9]],
    post:["Serve with berries and Greek yogurt"] },
  { id:"mix", name:"Protein Pancake & Waffle Mix", app:"griddle", cat:"sweet", serves:4, kcal:433, p:35, c:58, f:9, bg:"#b07a3c", food:["#d9a560","#f4ead7","#7a2e4a"], isNew:true,
    src:{ site:"Smart Nutrition", title:"High Protein Pancakes: DIY Power Cakes Mix", url:"https://smartnutrition.ca/high-protein-pancakes-diy-power-cakes-mix/", stars:4.56, n:9 },
    change:"Serving size is ours: the full batch makes 4 big servings.",
    pre:["Heat griddle or waffle iron"],
    ing:[[[[1, "cup", 80]], "rolled oats"], [[[1.5, "cup", 180.0]], "whole-wheat flour"], [[[1, "cup", 75]], "whey protein isolate"], [[[4.5, "tsp", 12.2]], "buttermilk powder (optional)"], [[[1, "tbsp", 13]], "brown sugar"], [[[1, "tbsp", 12]], "baking powder"], [[[0.5, "tsp", 3.0]], "salt"], [[[1.75, "cup", 427.0]], "milk"], [[[3, "", 150]], "eggs"]],
    tree:["cook as pancakes or waffles",["whisk",["whisk; store airtight",["blend to flour",0],1,2,3,4,5,6],7,8]],
    post:["Smaller batch: 1 cup mix + ½ cup milk + 1 egg"] },
  { id:"brownies", name:"Greek Yogurt Brownies", app:"airfryer", cat:"sweet", serves:4, kcal:79, p:9, c:11, f:4, bg:"#4a2c1e", food:["#5c3a26","#3b2418","#f4ead7"], isNew:true,
    src:{ site:"Matt's Fit Chef", title:"Flourless Greek Yogurt Brownies", url:"https://mattsfitchef.com/flourless-greek-yogurt-brownies/", stars:4.6, n:158 },
    change:"Source bakes in the oven. Our air fryer option: 320°F for about 20 min (check with a toothpick). Stir in a scoop of chocolate whey for about +6 g protein per serving.",
    pre:["Preheat oven to 350°F; line a 6×6-in pan with parchment"],
    ing:[[[[0.75, "cup", 180.0]], "plain Greek yogurt"], [[[1, "", 50]], "egg"], [[[0.5, "cup", 60.0]], "cocoa powder"], [[[0.4, "cup", 80.0]], "granulated erythritol"], [[[0.5, "tsp", 0.5], ["pinch", "", null]], "coffee powder and salt (optional)"], [[["handful", "", null]], "chocolate chips (optional)"]],
    tree:["cool fully, then cut",["bake 22–30 min",["pour into pan, top",["mix until smooth",0,1,2,3,4],5]]],
    post:["Keeps 4 days in the fridge"] },
  { id:"muffins", name:"Greek Yogurt Blueberry Protein Muffins", app:"oven", cat:"sweet", serves:6, kcal:342, p:20, c:38, f:12, bg:"#3d4f8a", food:["#e3b878","#f4ead7","#3b3f8f"], isNew:true,
    src:{ site:"Real Life Nutritionist", title:"High Protein Blueberry Muffins", url:"https://reallifenutritionist.com/high-protein-blueberry-muffins/", stars:5, n:22 },
    change:"Makes 12 muffins; a serving is 2. For more protein we swapped ¼ cup flour for whey, used nonfat Greek yogurt, and traded some oil for extra yogurt (source: 8 g protein per muffin, ours about 10 g).",
    pre:["Preheat oven to 350°F; line a 12-cup muffin pan"],
    ing:[[[[1.25, "cup", 156]], "all-purpose flour"], [[[0.75, "cup", 75]], "vanilla whey protein"], [[[1, "tsp", 4]], "baking powder"], [[[0.5, "tsp", 2.3]], "baking soda"], [[[0.5, "tsp", 3.0]], "salt"], [[[1, "cup", 148]], "blueberries"], [[[1.25, "cup", 306]], "nonfat plain Greek yogurt"], [[[0.33, "cup", 107]], "maple syrup"], [[[0.25, "cup", 54]], "olive oil"], [[[2, "tsp", 8]], "vanilla extract"], [[[2, "large", 100]], "eggs"]],
    tree:["cool 10 min in pan, then on a rack",["bake 18–22 min, until a toothpick comes out clean",["fold until just combined; fill 12 cups",["toss to coat",["whisk",0,1,2,3,4],5],["whisk until smooth",6,7,8,9,10]]]],
    post:["Keeps 4 days in the fridge or 3 months frozen", "Add a cup of Greek yogurt for about 43 g protein"] },
  { id:"rice", name:"Cilantro Lime Rice", app:"stovetop", cat:"side", serves:4, kcal:219, p:3, c:37, f:6, bg:"#7fae4a", food:["#fffaf2","#4f7a2e","#e8c77a"],
    src:{ site:"Family Fresh Meals", title:"Copycat Chipotle Cilantro Lime Rice", url:"https://www.familyfreshmeals.com/copycat-chipotle-cilantro-lime-rice/", stars:4.94, n:32 },
    ing:[[[[1, "tbsp", 14.2]], "butter"], [[[1, "", null]], "bay leaf"], [[[1, "cup", 185]], "basmati rice"], [[[2, "cup", 480]], "water"], [[[1, "tsp", 6]], "salt"], [[[1, "tbsp", 14.2]], "butter"], [[[2, "tbsp", 2]], "fresh cilantro, chopped"], [[[1.5, "tbsp", 22.5]], "fresh lime juice"], [[[1, "tbsp", 15]], "fresh lemon juice"]],
    tree:["stir in; remove bay leaf",["simmer covered 15–17 min",["bring to a boil",["sauté 2 min, stirring",0,1,2],3,4]],5,6,7,8] },
  { id:"broccoli", name:"Air Fryer Broccoli", app:"airfryer", cat:"side", serves:3, kcal:131, p:4, c:10, f:10, bg:"#3f7a2e", food:["#5d9a3a","#3f6b2a","#f2c14e"],
    src:{ site:"Well Plated", title:"Air Fryer Broccoli", url:"https://www.wellplated.com/air-fryer-broccoli/", stars:4.55, n:22 },
    pre:["Preheat air fryer to 400°F (about 3 min)"],
    ing:[[[[1, "lb", 454]], "broccoli florets, cut small"], [[[2, "tbsp", 27.0]], "extra-virgin olive oil"], [[[0.5, "tsp", 1.5]], "kosher salt"], [[[0.25, "tsp", 0.8]], "garlic powder"], [[[0.25, "tsp", 0.6]], "black pepper"], [[[0.25, "tsp", 1.0]], "sugar (optional)"], [[[2, "tbsp", 30]], "water, into the basket"]],
    tree:["top with lemon or Parmesan",["air fry 4 min, toss, 4–8 min more",["toss to coat",0,1,2,3,4,5],6]] },
  { id:"sweetpotato", name:"Air Fryer Sweet Potato Cubes", app:"airfryer", cat:"side", serves:4, kcal:143, p:2, c:23, f:5, bg:"#d9692b", food:["#f08a3c","#c0561f","#4f7a2e"],
    src:{ site:"Well Plated", title:"Air Fryer Sweet Potato Cubes", url:"https://www.wellplated.com/air-fryer-sweet-potato-cubes/", stars:5, n:7 },
    ing:[[[[1, "lb", 454]], "sweet potatoes, ½-inch cubes"], [[[1.5, "tbsp", 20.2]], "extra-virgin olive oil"], [[[0.75, "tsp", 2.2]], "kosher salt"], [[[0.5, "tsp", 1.1]], "smoked paprika"], [[[0.5, "tsp", 1.5]], "garlic powder"], [[[0.25, "tsp", 0.6]], "black pepper"]],
    tree:["salt to taste",["air fry 400°F about 12 min, shake halfway",["toss",0,1,2,3,4,5]]] },
  { id:"mash", name:"Greek Yogurt Mashed Potatoes", app:"stovetop", cat:"side", serves:6, kcal:171, p:5, c:27, f:5, bg:"#c9a24a", food:["#f4ead7","#e8c77a","#4f7a2e"],
    src:{ site:"Hey Nutrition Lady", title:"Greek Yogurt Mashed Potatoes", url:"https://www.heynutritionlady.com/greek-yogurt-mashed-potatoes/", stars:4.9, n:9 },
    ing:[[[[2, "lb", 907]], "Yukon Gold potatoes, 1-inch pieces"], [[[1, "cup", 240]], "vegetable broth"], [[[2, "tbsp", 28.4]], "butter"], [[[0.5, "cup", 122.5]], "full-fat Greek yogurt"], [[[2, "tbsp", 6]], "chives or green onion, chopped"], [[["to taste", "", null]], "salt and black pepper"]],
    tree:["season; thin with saved broth if dry",["mix in",["roughly mash",["drain, save the liquid",["simmer covered about 15 min",0,1]]],2,3,4],5] },
  { id:"greek", name:"Greek Salad", app:"salad", cat:"side", serves:4, kcal:259, p:6, c:12, f:22, bg:"#2f6f8f", food:["#d9482b","#7fae4a","#fffaf2"],
    src:{ site:"Downshiftology", title:"Best Greek Salad", url:"https://downshiftology.com/recipes/greek-salad/", stars:4.97, n:108 },
    change:"We halved the dressing oil from ½ cup to ¼ cup (saves about 120 kcal per serving).",
    ing:[[[[1, "large", 300]], "cucumber, diced"], [[[1, "pint", 300]], "grape tomatoes, halved"], [[[1, "", 150]], "green bell pepper, diced"], [[[0.5, "", 75.0]], "red onion, thinly sliced"], [[[0.5, "cup", 67.5]], "Kalamata olives, halved"], [[[4, "oz", 113]], "feta, crumbled"], [[["to taste", "", null]], "salt and black pepper"], [[[0.3333333333333333, "cup", 80.0]], "red wine vinegar"], [[[1, "", 45]], "lemon, juiced"], [[[1, "tsp", 5]], "Dijon mustard"], [[[2, "", 8]], "garlic cloves, minced"], [[[0.5, "tsp", 0.5]], "dried oregano"], [[[0.25, "tsp", 1.5], [0.25, "tsp", 0.6]], "salt and black pepper"], [[[0.25, "cup", 54.0]], "olive oil"]],
    tree:["toss gently",["combine in a large bowl",0,1,2,3,4,5,6],["whisk in oil slowly",["whisk",7,8,9,10,11,12],13]] },
  { id:"beansalad", name:"Black Bean & Corn Salad", app:"salad", cat:"side", serves:8, kcal:233, p:6, c:26, f:13, bg:"#3b2a20", food:["#2b1d14","#f2c14e","#7fae4a"],
    src:{ site:"Once Upon a Chef", title:"Black Bean Salad with Corn, Avocado & Lime Vinaigrette", url:"https://www.onceuponachef.com/recipes/black-bean-salad-with-corn-red-peppers-avocado-lime-cilantro-vinaigrette.html", stars:4.9, n:312 },
    change:"We cut the olive oil from ½ cup + 1 tbsp to ¼ cup (saves about 75 kcal per serving).",
    ing:[[[[3, "ear", 270]], "fresh corn"], [[[2, "can (15 oz)", 850]], "black beans, drained and rinsed"], [[[2, "", 300]], "red bell peppers, diced"], [[[2, "", 8]], "garlic cloves, minced"], [[[2, "tbsp", 20]], "shallots, minced"], [[[2, "tsp", 12]], "salt"], [[[0.25, "tsp", 0.5]], "cayenne pepper"], [[[2, "tbsp", 25.0]], "sugar"], [[[0.25, "cup", 54.0]], "extra-virgin olive oil"], [[[1, "tsp", 2]], "lime zest"], [[[0.375, "cup", 90.0]], "fresh lime juice"], [[[0.5, "cup", 8.0]], "fresh cilantro, chopped"], [[[2, "", 300]], "avocados, chopped"]],
    tree:["fold in just before serving",["chill several hours",["mix well",["boil 3–4 min, ice bath, cut off kernels",0],1,2,3,4,5,6,7,8,9,10,11]],12] },
  { id:"zucchini", name:"Grilled Zucchini with Parmesan", app:"grill", cat:"side", serves:4, kcal:79, p:4, c:7, f:5, bg:"#4f7a2e", food:["#7fae4a","#3f6b2a","#f4ead7"],
    src:{ site:"Well Plated", title:"Grilled Zucchini with Parmesan and Herbs", url:"https://www.wellplated.com/grilled-zucchini/", stars:4.74, n:34 },
    pre:["Heat grill to 400–450°F"],
    ing:[[[[4, "medium", 908]], "zucchini (8 oz each)"], [[[1, "tbsp", 13.5]], "extra-virgin olive oil"], [[[1, "tsp", 1]], "Italian seasoning (optional)"], [[[1, "tsp", 3]], "kosher salt"], [[[0.5, "tsp", 1.1]], "black pepper"], [[[0.5, "small", 15.0]], "lemon, juiced"], [[[2, "tbsp", 10]], "Parmesan, freshly grated"]],
    tree:["squeeze and sprinkle on",["grill cut side 4 min, skin side 5 min",["drizzle and season",["trim, quarter lengthwise",0],1,2,3,4]],5,6] },
  { id:"corn", name:"Skinny Mexican Grilled Corn", app:"grill", cat:"side", serves:4, kcal:119, p:6, c:18, f:4, bg:"#e0a91f", food:["#f2c14e","#fffaf2","#4f7a2e"],
    src:{ site:"Bless Her Heart Y'all", title:"Skinny Mexican Grilled Corn", url:"https://blessherheartyall.com/skinny-mexican-grilled-corn/", stars:null, n:null },
    pre:["Heat grill to medium-high"],
    ing:[[[[4, "ear", 800]], "corn, shucked"], [[["light coat", "", null]], "olive oil"], [[[2, "tbsp", 30]], "Greek yogurt"], [[[0.25, "tsp", 0.7]], "chili powder"], [[[0.125, "tsp", 0.3]], "paprika"], [[[0.125, "tsp", 0.4]], "cumin, black pepper and salt, combined"], [[[0.25, "cup", 25.0]], "grated Parmesan"], [[[0.25, "cup", 4.0]], "fresh cilantro, chopped"], [[[0.5, "", 30.0]], "lime, in wedges"]],
    tree:["sprinkle on, squeeze lime over",["spread on hot corn",["grill 10–12 min, turning often",0,1],["mix",2,3,4,5]],6,7,8] }
];
/* Recommended sides for each main: [side id, why it fits]. */
const PAIRS = {
  salsa:[["rice","Turns it into a burrito bowl"],["beansalad","Adds fiber and crunch"]],
  chili:[["corn","A classic next to chili"],["sweetpotato","Smoky-sweet with the spice"]],
  barbacoa:[["rice","The Chipotle-style pairing"],["beansalad","Fresh lime to cut the richness"]],
  tikka:[["rice","Soaks up the sauce"],["broccoli","A quick green vegetable"]],
  whitechili:[["corn","Same southwest flavors"],["broccoli","A quick green vegetable"]],
  honeygarlic:[["rice","Catches the honey-garlic glaze"],["broccoli","Balances the sweet sauce"]],
  salmon:[["rice","Classic with soy-glazed fish"],["broccoli","Same air fryer, same temperature"]],
  parm:[["mash","A comfort-food plate"],["greek","Bright and fresh next to the crust"]],
  meatballs:[["zucchini","A light swap for pasta"],["greek","Fresh crunch on the side"]],
  shrimp:[["rice","Stretches the dish into a full meal"],["corn","Southern-style with Cajun spice"]],
  tofu:[["rice","Rounds out the bowl"],["broccoli","Air fry it right after the tofu"]],
  fajitas:[["rice","Burrito bowl base"],["beansalad","Adds fiber and protein"]],
  flank:[["mash","Steak and potatoes"],["zucchini","Grill it alongside the steak"]],
  souvlaki:[["greek","The Greek classic"],["rice","Fills out the plate with the tzatziki"]],
  pork:[["sweetpotato","Sweet-smoky with the spice rub"],["zucchini","Grill it alongside the pork"]],
  teriyaki:[["rice","Catches the teriyaki sauce"],["broccoli","The takeout-style pairing"]],
  burger:[["sweetpotato","A lighter swap for fries"],["corn","Cookout classic"]]
};
const ADDONS = [
  { id:"yogurt", name:"Greek yogurt, 1 cup", kcal:130, p:23, c:9, f:0 },
  { id:"cottage", name:"Cottage cheese, 1 cup", kcal:180, p:28, c:8, f:5 },
  { id:"eggs", name:"Eggs, 3 large", kcal:215, p:19, c:1, f:15 },
  { id:"whites", name:"Egg whites, 1 cup", kcal:125, p:26, c:2, f:0 },
  { id:"edamame", name:"Edamame, 1 cup", kcal:190, p:18, c:14, f:8 },
  { id:"lentils", name:"Lentils, 1 cup cooked", kcal:230, p:18, c:40, f:1 },
  { id:"tuna", name:"Tuna in water, 5 oz", kcal:130, p:30, c:0, f:1 },
  { id:"whey", name:"Whey or casein scoop", kcal:120, p:24, c:3, f:1 }
];
const ALL = Object.fromEntries([...RECIPES, ...ADDONS].map(x => [x.id, x]));
const APP_LABEL = { crockpot:"Crockpot", airfryer:"Air fryer", grill:"Grill", griddle:"Griddle", stovetop:"Stovetop", salad:"Salad", oven:"Oven" };
const EXAMPLE = [["mix",1],["salsa",1],["souvlaki",1],["yogurt",1]];
